# Generated by Django 5.2.7 on 2025-11-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_email_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
