# Generated by Django 5.2.7 on 2025-11-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_is_private_report_block'),
        ('chat', '0004_remove_userprofile_email_remove_userprofile_phone'),
    ]

    operations = [
    ]
